export const ADD_LIST = 'ADD_LIST';

export const ADD_TASK_TO_LIST = 'ADD_TASK_TO_LIST';

export const REMOVE_TASK_FROM_LIST = 'REMOVE_TASK_FROM_LIST';

export const UPDATE_TASK = 'UPDATE_TASK';

export const UPDATE_IS_FINISHED_IN_TASK = 'UPDATE_IS_FINISHED_IN_TASK';

export const UPDATE_IS_IMPORTANT_IN_TASK = 'UPDATE_IS_IMPORTANT_IN_TASK';

export const UPDATE_MY_DAY_SCREEN = 'UPDATE_MY_DAY_SCREEN';

export const ADD_SUBTASK = 'ADD_SUBTASK';

export const UPDATE_SUBTASK = 'UPDATE_SUBTASK';

export const DELETE_SUBTASK = 'DELETE_SUBTASK';

export const UPDATE_IS_DONE_SUBTASK = 'UPDATE_IS_DONE_SUBTASK';
